# Generated by Django 4.1.3 on 2022-11-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="favorites",
            new_name="favourites",
        ),
    ]
