# Generated by Django 4.1.3 on 2022-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="default_missingno.png", upload_to="pokemon_pics"
                    ),
                ),
            ],
        ),
    ]
