# Generated by Django 4.1.3 on 2022-11-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0002_pokemon_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
