# Generated by Django 4.1.3 on 2022-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0003_alter_pokemon_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
