# Generated by Django 4.1.3 on 2022-11-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0004_alter_pokemon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
