# Generated by Django 4.1.3 on 2022-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemons", "0005_alter_pokemon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="attack",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="defense",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="hp",
            field=models.PositiveIntegerField(default=1, verbose_name="Hit Points"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="sp_atk",
            field=models.PositiveIntegerField(default=1, verbose_name="Special Attack"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="sp_def",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Special Defense"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="speed",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
